language: node_js
node_js:
  - 9.11.1

git:
  depth: 3

cache:
  pip: true
  directories:
    - node_modules

install:
  - pip install grow --user
  - npm install -g gulp-cli
  # - npm install -g firebase-tools
  - npm install

jobs:
  include:
    - stage: build
      script:
        - ./build_scripts/build.sh None en de es
    - stage: build
      script:
        - ./build_scripts/build.sh fr id ja
    - stage: build
      script:
        - ./build_scripts/build.sh it ko pt_BR
    - stage: build
      script:
        - ./build_scripts/build.sh tr zh_CN ru
    - stage: deploy
      install:
        - npm install -g firebase-tools
      script:
        - ./build_scripts/deploy.sh
branches:
  only:
  - production
  - master
  - parallel

env:
  global:
    secure: RRx3CaLmCC0rA+MOYXTI3HTAMc2TI9AQcodUfZhr+vNEL8d0q09EZkYU/TjkRx9VQ1paOT1AmxNQJtHhysIS7B/pSAZoNG9bPC5UXmiZHVLbRB4qPmMMte9zdfKanGY3/g3zt2qOTUVVL4ymDy5xK2uYZ/KgkrDx1gGH3mSoTO6gK79I4nisJYDcRfzI/UUvrNkdjlFYrFnZbnMdnqZSryuv7CrdZWpYtLDryzJ+bcgq6Vr2liiKwmVb+/tff3EblAzBcWMAM4I0MzRaM+Mahw0EEENc24brtVoQTbvSdXXJ9CEIfWjykSyZh0WrZkx3tKY95GDr9PCHEkyI5d2kUGYDbRjjrEuBEdPTcjx6zZ2vXUlVPeDxNwLO1WZwVy0Om1dg/jwPjVDtsubjBaC+4XezJCywaZruGD6Q0iStemMVapN19SbGJzo9uYG8EvVB4OFlmY2l/fOadTIC9YHpYJREhGc2DBW9jHfTK1dgyW1JpnFgieEOSw24gsvbxSSV5db7tJU36Pt1Kkcu3IZnYyHlBUmYKZ24cizh6azfkHRaLvSvdJuvx0euuoz/WOJ77toUD6wPc0/OtrKnkCfQowtciMdnKNhuu4JpegdZ9gQqpV2gQ0XpPgxc4afKCd0L5QiUNFCu1J+fQ0obclqWZpC0VzHdDpNMckv4I7XqnhI=
